Add Turbine coil and Datapack pages
BiggerSeries/Wiki pull request #2
Opened 2022-08-30 08:31 UTC by Mitchell5200

2022-08-30 23:37 UTC, gizmocodes commented on biggerreactors/turbine/coils.md
> +Turbine Coils
Redundant page title, can be removed.

2022-08-30 23:37 UTC, gizmocodes approved these changes
Looks good to me for the most part, just need to rmeove the redundant page title in coils.md.

2022-08-31 01:46 UTC, Mitchell5200 commented
Extra Title removed

2022-09-04 18:36 UTC, RogueLogix requested changes

2022-09-04 18:36 UTC, RogueLogix commented on biggerreactors/datapacks.md
> +Example file, in this case `lapis_block.json5`, this one needs to be placed into the folder `\ebcr\moderators\`
worth noting that .json5 is not a requirement, normal .json can be used too

2022-09-04 18:36 UTC, RogueLogix commented on biggerreactors/reactor/moderators.md
> +*The below information is accurate for Bigger Reactors 0.5.x (1.16) and 0.6.x (1.17-1.19), the simulation changes in 0.7.x (1.20+)*
what the values do is valid for 0.6.x and earlier, what the values are changed with 0.5, _a little bit_

2022-09-04 18:36 UTC, RogueLogix commented on biggerreactors/turbine/coils.md
> +*The below information is accurate for Bigger Reactors 0.5.x (1.16) and 0.6.x (1.17-1.19), the simulation changes in 0.7.x (1.20+)*
much like with the moderators, this is accurate for earlier than 0.5 too, and here i don't think i changed the values used either

2022-09-04 18:36 UTC, RogueLogix commented on biggerreactors/turbine/coils.md
> +- **Bonus**: Applies a final RF bonus onto the outputted RF value *(i think, based on the sim code)*.
efficiency and bonus are actually the other way around from whats described here (and tbf, what i told you earlier)
```
double inductionTorque = rpm * inductorDragCoefficient /*extraction rate avg*/ * coilSize;
double energyToGenerate = Math.pow(inductionTorque, inductionEnergyExponentBonus /* bonus avg*/) * inductionEfficiency /* efficiency avg*/;
```

2022-09-04 18:36 UTC, RogueLogix commented on biggerreactors/datapacks.md
> +In my Examples i've used [KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs) and put the files in the directory `kubejs\data\biggerreactors\`
behavior isn't noted anywhere, and it should be, the datapack loader will look in all namespaces, so biggerreactors vs kubsjs vs whatever for the namespace doesn't matter

2022-09-09 03:52 UTC, Mitchell5200 commented on biggerreactors/datapacks.md
> +Example file, in this case `lapis_block.json5`, this one needs to be placed into the folder `\ebcr\moderators\`
Note added on line 11

2022-09-09 04:00 UTC, RogueLogix commented on biggerreactors/datapacks.md
> +In my Examples i've used [KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs) and put the files in the directory `kubejs\data\biggerreactors\`
im dumb, sorta, it does look across all datapacks, but namespace (first directory after "data") does matter, and it does look for specifically "biggerreactors", just as a secondary sanity to ensure that i dont step on anyone elses data
so, for `*/data/biggerreactors/ebcr/moderators/*/*.json*`. in the mod dev environment, that is `resoruces/data/biggerreactors/ebcr/moderators/*/*.json*)`, unsure when outside moddev

ResourceLocations make this weird, because assets and data handles the namespace a bit different, specifically where assets adds to path based on context. that said, path it really doesnt care about, and it will load any and all subdirectories

2022-09-09 06:04 UTC, RogueLogix approved these changes

2022-09-09 06:05 UTC, merged